### ISSUE TITLE
Ray storage dir cannot be created

### ISSUE THREAD

**Issue by dominik-handler** [hpcaitech/FastFold#107]
Hi,

on our cluster the current method to generate the path for the ray directory is not working. It seems that os.getlogin() does not result in a  meaningful value. 
`storage_dir = "file:///tmp/ray/" + os.getlogin() + "/workflow_data"`
I get back an OS error that the device does not exist. 

After removing os.getlogin() the workflow initiates properly. 
Would it be possible to define the ray-storage dir via a flag like the ouput dir? 

Thank you and all the best,
Dominik

**Comment by oahzxl** [comment]
Good suggestion. We can use timestamp to create the dir.
