### ISSUE TITLE
pdb_seqres.txt parse error when execute hmmsearch

### ISSUE THREAD

**Issue by ssn1771** [hpcaitech/FastFold#113]
hi, i met a  parse error when executing hmmsearch in pdb_seqres.txt. the log is:

(WorkflowManagementActor pid=7511) RuntimeError: hmmsearch failed:
(WorkflowManagementActor pid=7511) stdout:
(WorkflowManagementActor pid=7511) # hmmsearch :: search profile(s) against a sequence database
(WorkflowManagementActor pid=7511) # HMMER 3.3.2 (Nov 2020); http://hmmer.org/
(WorkflowManagementActor pid=7511) # Copyright (C) 2020 Howard Hughes Medical Institute.
(WorkflowManagementActor pid=7511) # Freely distributed under the BSD open source license.
(WorkflowManagementActor pid=7511) # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(WorkflowManagementActor pid=7511) # query HMM file:                  /tmp/tmph1wus5n3/query.hmm
(WorkflowManagementActor pid=7511) # target sequence database:        /uniprot/pdb_seqres.txt
(WorkflowManagementActor pid=7511) # MSA of all hits saved to file:   ./alignments/5ZNG_1|Chain A|NBS-LRR type protein|Oryza sativa subsp. japonica (39947)/hmm_output.sto
(WorkflowManagementActor pid=7511) # show alignments in output:       no
(WorkflowManagementActor pid=7511) # sequence reporting threshold:    E-value <= 100
(WorkflowManagementActor pid=7511) # domain reporting threshold:      E-value <= 100
(WorkflowManagementActor pid=7511) # sequence inclusion threshold:    E-value <= 100
(WorkflowManagementActor pid=7511) # domain inclusion threshold:      E-value <= 100
(WorkflowManagementActor pid=7511) # MSV filter P threshold:       <= 0.1
(WorkflowManagementActor pid=7511) # Vit filter P threshold:       <= 0.1
(WorkflowManagementActor pid=7511) # Fwd filter P threshold:       <= 0.1
(WorkflowManagementActor pid=7511) # number of worker threads:        12
(WorkflowManagementActor pid=7511) # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(WorkflowManagementActor pid=7511) 
(WorkflowManagementActor pid=7511) Query:       query  [M=137]
(WorkflowManagementActor pid=7511) 
(WorkflowManagementActor pid=7511) 
(WorkflowManagementActor pid=7511) stderr:
(WorkflowManagementActor pid=7511) Parse failed (sequence file /uniprot/pdb_seqres.txt):
(WorkflowManagementActor pid=7511) Line 1366526: illegal character 0

**Comment by Shenggan** [comment]
You can try to re-download `pdb_seqres.txt`, or refer this issue https://github.com/deepmind/alphafold/issues/560

**Comment by ssn1771** [comment]
thanks, removing the lines including "0" works
