### ISSUE TITLE
Function not accessible 

### ISSUE THREAD

**Issue by georgkempf** [hpcaitech/FastFold#123]
Hi, I stumbled over an issue when using monomer_ptm model. The function LinearParams used here

https://github.com/hpcaitech/FastFold/blob/f55dca95b99a052ea18b685548668f60cbe54d79/fastfold/utils/import_weights.py#L566

is defined in a different scope (L144) and cannot be accessed in this place.

**Comment by Shenggan** [comment]
Thanks for reporting, fixed in #124
