### ISSUE TITLE
problem with multimer mode, ValueError: Could not parse description:

### ISSUE THREAD

**Issue by wh277** [hpcaitech/FastFold#151]
running in multimer mode...
Finished running alignment for 1_1
Finished running alignment for 1_2
Finished running alignment for 1_3
Finished running alignment for 1_4
Traceback (most recent call last):
  File "inference.py", line 548, in <module>
    main(args)
  File "inference.py", line 164, in main
    inference_multimer_model(args)
  File "inference.py", line 281, in inference_multimer_model
    feature_dict = data_processor.process_fasta(
  File "/home/fy/FastFold-main/fastfold/data/data_pipeline.py", line 1165, in process_fasta
    chain_features = self._process_single_chain(
  File "/home/fy/FastFold-main/fastfold/data/data_pipeline.py", line 1114, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process_fasta(
  File "/home/fy/FastFold-main/fastfold/data/data_pipeline.py", line 936, in process_fasta
    hits = self._parse_template_hits(
  File "/home/fy/FastFold-main/fastfold/data/data_pipeline.py", line 884, in _parse_template_hits
    hits = parsers.parse_hmmsearch_sto(
  File "/home/fy/FastFold-main/fastfold/data/parsers.py", line 656, in parse_hmmsearch_sto
    template_hits = parse_hmmsearch_a3m(
  File "/home/fy/FastFold-main/fastfold/data/parsers.py", line 627, in parse_hmmsearch_a3m
    metadata = _parse_hmmsearch_description(hit_description)
  File "/home/fy/FastFold-main/fastfold/data/parsers.py", line 589, in _parse_hmmsearch_description
    raise ValueError(f'Could not parse description: "{description}".')
ValueError: Could not parse description: "0000|3jqh_A/8-65 [subseq from] mol:protein length:167  C-type lectin domain family 4 member M".

**Comment by Gy-Lu** [comment]
Hi, I think drop "0000|" in your description of fasta file may solve your problem, i.e.
>3jqh_A/8-65
SOMESEQUENCE

**Comment by wh277** [comment]
thanks，I will try it

**Comment by Gy-Lu** [comment]
Hello, there should be a `>` before the discription, I updated my comment because GitHub explained it as a quote symbol :-\

**Comment by wh277** [comment]
OK, thanks

**Comment by wh277** [comment]
It works. But another problem appears.    raise ValueError(f"hit.name did not start with PDBID_chain: {hit.name}")
ValueError: hit.name did not start with PDBID_chain: 6qq_A.
 6qq is a small molecule in PDB, not a protein, there are other small molecules in hmm_output.sto, not only one.
 do you know how to solve it?

**Comment by Gy-Lu** [comment]
Hi, I am not sure either.
Could you share the content of your fasta file? It would be really helpful to me to debug.

**Comment by wh277** [comment]
OK, it contains 2 same sequences. 
>1_1
MNDQARSVLTTVLEEGAWSVRQWPGDAAAETVHSALGRVTDLGDRVQGIAYTTSGAMSVHTATPELTTRLDGRDQPIPLDSVYELRLWAVIDGRADDGLLAHELRWLNGSGTAEIRVGGQELLSANGDAGWQTTRCWTRSNSYLQHGATAPFDEPSKAMTSVEVFTEEPTYGNTVFVDEIMTGRWS
>1_2
MNDQARSVLTTVLEEGAWSVRQWPGDAAAETVHSALGRVTDLGDRVQGIAYTTSGAMSVHTATPELTTRLDGRDQPIPLDSVYELRLWAVIDGRADDGLLAHELRWLNGSGTAEIRVGGQELLSANGDAGWQTTRCWTRSNSYLQHGATAPFDEPSKAMTSVEVFTEEPTYGNTVFVDEIMTGRWS

**Comment by wh277** [comment]
Today, I encountered  bugs when using the native AlphaFold2 to predict a complex. I suspect it might be caused by the pdb_seqres.txt file, which contains non-protein data.

**Comment by wh277** [comment]
I fixed the file, and now try FastFold again. It's my fault, the file was not downloaded by script in alphafold. sorry about it. https://github.com/deepmind/alphafold/issues/623#issuecomment-1310651450

**Comment by wh277** [comment]
Now, no problem with multimer mode.  There were some bad data in my old pdb_seqres.txt, after I re-downloaded the file, it works well. But I also met this: https://github.com/hpcaitech/FastFold/issues/144#issue-1567588496
