### ISSUE TITLE
Bugfixes need to be pulled from the OpenFold repo

### ISSUE THREAD

**Issue by gahdritz** [hpcaitech/FastFold#17]
Hey there! I just wanted to flag that we recently fixed a bunch of bugs in OpenFold's template code (as of OpenFold commit #[591d10d](https://github.com/aqlaboratory/openfold/commit/591d10d26765d5413f2d79a2454764735ba4b376)), which I noticed are also present here. These have a significant effect on the quality of predictions, especially for chains with small MSAs.

**Comment by Shenggan** [comment]
Thank you very much, we have synchronized the changes. 
OpenFold is a great project, thanks for the help with the reproduction of AlphaFold!
