### ISSUE TITLE
Invalid resolution format: ['?']

### ISSUE THREAD

**Issue by HF06** [hpcaitech/FastFold#171]
Hi, when i run the multimer inference, i have encountered "Invalid resolution format: ['?']" error. could anybody help me to deal with the error issues?
[03/30/23 09:19:58] INFO     colossalai - root - INFO: Found an exact template match 3buk_B.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/1bnd.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             YAEHKSHRGEVSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTQNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
                    INFO     colossalai - root - INFO: Invalid resolution format: ['?']                                                             
                    INFO     colossalai - root - INFO: Found an exact template match 1bnd_B.

And this error leads to another error "torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGSEGV" in inference_multimer_model (inference.py line293: torch.multiprocessing.spawn(inference_model, nprocs=args.gpus, args=(args.gpus, result_q, batch, args)))

**Comment by Gy-Lu** [comment]
Hi, as I know, this error is usually raised when the input is not valid or the losing part of databases.

**Comment by HF06** [comment]
> Hi, as I know, this error is usually raised when the input is not valid or the losing part of databases.

Thank you for your reply. I wonder what format of input should be. My input is like following:
>AAA63231.1 neurotrophin-3 [Homo sapiens]
MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPR
EPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYLMEDYVGSPVVANRTSRRKRYA
EHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDD
KHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
>AAA63231.1 neurotrophin-3 [Homo sapiens]
MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPR
EPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYLMEDYVGSPVVANRTSRRKRYA
EHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDD
KHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT

Is there any problems about my input. Inference of monomer is ok. It may not be due to the losing part of databases.

**Comment by Gy-Lu** [comment]
I recommend you add `>` before the tagline and not using special char in the tag, such as:
```
>AAA63231_1
MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPR
EPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYLMEDYVGSPVVANRTSRRKRYA
EHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDD
KHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
>AAA63231_2
MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPR
EPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYLMEDYVGSPVVANRTSRRKRYA
EHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDD
KHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
```
By the way, using the same tag would cause some undefined behavior.
If you got other problems, plz let me know.

**Comment by HF06** [comment]
Thanks. I have resolved my problems. It seemed to be the environment problems. Yes, using the same tag results to an output of monomer maybe because of deletion of the alignments.

**Comment by HF06** [comment]
BTW, I have run the training script, it seems lacking a required argument: --obsolete_pdbs_file_path.
