### ISSUE TITLE
Cannot run perf.py in benchmark

### ISSUE THREAD

**Issue by chuhan-ouyang** [hpcaitech/FastFold#176]
When running perf.py in the benchmark folder, the code could not compile because the Evoformer constructor got an unexpected argument "d_node." There seems to be a mismatch between the Evoformer constructor's declared list of arguments (/fastfold/model/fastnn/evoformer.py) and its provided arguments in benchmark/perf.py

![Evoformer Constructor Declaration](https://github.com/hpcaitech/FastFold/assets/112202738/16d409f6-ac79-43c0-8292-9cf7b978f6c8)
![Mismatch in Perf py](https://github.com/hpcaitech/FastFold/assets/112202738/bc631af2-78ad-4221-a5cd-e7f1f8c66875)
![Usage of Evoformer Constructor](https://github.com/hpcaitech/FastFold/assets/112202738/3ebc6905-e03f-47e4-bebd-ffb0eae90f39)

**Comment by Gy-Lu** [comment]
Hi, I have fixed it in #177.
If there are still bugs, feel free to reopen this issue.

**Comment by chuhan-ouyang** [comment]
Thank you very much for the fix! I ran into a new issue in #178, could you confirm whether that is still an error related to the CLI/interface, please?
