### ISSUE TITLE
Trouble Running Perf.py in Benchmark

### ISSUE THREAD

**Issue by chuhan-ouyang** [hpcaitech/FastFold#178]
Hi,

After the fix to the perf.py CLI issue, there is still a problem in running the file. It seems to be a mismatch between the size of the parameters between the layers. 
![image](https://github.com/hpcaitech/FastFold/assets/112202738/4dce6afe-8194-4d4f-b50c-17380324ba5d)

**Comment by Gy-Lu** [comment]
Hi, but I can not reproduce this problem.
If you want to examine the shape, just print the tensor shape before this line:
![image](https://github.com/hpcaitech/FastFold/assets/74758262/481ec67b-f5b2-4117-876f-0fd9922401fa)

But I think it might be something wrong with your environment.
Here is some discussion about this problem which you can refer:
https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-invalid-value-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/124544/18

**Comment by chuhan-ouyang** [comment]
Fixed by running using CUDA 11.6 (CUDA 11.3 should also work).
