### ISSUE TITLE
Consider leveraging deepspeed

### ISSUE THREAD

**Issue by LifeIsStrange** [hpcaitech/FastFold#2]
https://github.com/microsoft/DeepSpeed
For even faster training :)

**Comment by Shenggan** [comment]
Thanks for suggestion. We chose [ColossalAI](https://github.com/hpcaitech/ColossalAI) for the distributed and training part of the process. ColossalAI includes DeepSpeed's key features and has excellent performance.

**Comment by LifeIsStrange** [comment]
Oh never heard about it, thanks for sharing.
I wonder which one of the two would yield to greatest speed increase.
Anyway it's nice to see those technologies evolve so fast!

**Comment by LifeIsStrange** [comment]
@Shenggan hello again, I'm not an expert but it seems colossalai has some optin support for the deepspeed algorithm ZERO2 and ZERO3
https://github.com/hpcaitech/ColossalAI/issues/682
hence you could try to enable those to see if it improve performance vs current baseline?

**Comment by Shenggan** [comment]
Thanks for the suggestion, FastFold currently relies on ColossalAI for parallel launch and process group management. It is an interesting proposal to try to introduce ZeRO technology in AlphaFold model training, and we will try to introduce ZeRO in subsequent training versions and compare the performance.
