### ISSUE TITLE
Warning: Torch did not find available GPUs on this system.

### ISSUE THREAD

**Issue by JOJO-wc-rabbit** [hpcaitech/FastFold#29]
Hi,

When I installed fastfold, I meet the following problem.

![image](https://user-images.githubusercontent.com/61336971/179915686-87395185-6ebf-4b24-a6d1-251c1ef2d791.png)

I think it's because I don't have a cuda environment on the cluster server (cpu node, non-root user) (but the code can be submitted to the gpu node to run). Is there any solution please?

Thanks！

**Comment by Shenggan** [comment]
I think you need CUDA environment to install fastfold. You can try to use `spack` install cuda for you non-root cpu node. Or you can submitted the installation to the gpu node.

If the cluster use environment module to manage the software stack, you can directly use some command like `module load cuda` on your cpu node.

**Comment by JOJO-wc-rabbit** [comment]
ok，thx！
