### ISSUE TITLE
About the inference performance

### ISSUE THREAD

**Issue by nnnwyn** [hpcaitech/FastFold#3]
Your work surely achieved a high performance in training of AlphaFold2.  i am wondering about the accuracy of your inference results. Have you made a benchmark of this part with AlphaFold2? Or can you publish your models for us to make a use of.

**Comment by Shenggan** [comment]
Currently FastFold focuses on providing a high-performance parallelizable Evoformer implementation to accelerate the training and inference of AlphaFold models. If inference is needed now, you still need to use the parameter weights officially released by AlphaFold, you can refer to [OpenFold](https://github.com/aqlaboratory/openfold).

We will try to add full inference and training capabilities to FastFold in the next few months.

**Comment by nnnwyn** [comment]
Olay, Thanks so much.
