### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by llwx593** [hpcaitech/FastFold#30]
Hi,
I try to run inference scripts using T1050.fasta(779 residues) on nvidia a100, the following table shows the in time.
<html>
<body>
<!DOCTYPE html><figure class="md-table-fig" cid="n214" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">

Type | Inference time
-- | --
FastFold | 262.14789s
OpenFold | 124.69651s

</figure><br class="Apple-interchange-newline">
</body>
</html>

It's a little different from the data in the paper. I don't know whether it's normal.
Thanks.

**Comment by Shenggan** [comment]
I think you can try the new code in main branch. Or you can send T1050.fasta to me, and I will have a performance test on our machines.

**Comment by Shenggan** [comment]
We run T1050.fasta on single A100 (80 GB PCIe) with new code in main branch (9ab281fea) , inference time of fastfold is 65.22272s. Here is the log: [inference-only.log](https://github.com/hpcaitech/FastFold/files/9572925/inference-only.log)

Issue closed, you can reopen this issue if you have further performance issues.
