### ISSUE TITLE
CUDA kernel bug

### ISSUE THREAD

**Issue by lupoglaz** [hpcaitech/FastFold#33]
This line does not seem correct:
[row_d_input = 0;](https://github.com/hpcaitech/FastFold/blob/9924e7be3737453cc9dba38055a6b9cc75e7c99d/fastfold/model/fastnn/kernel/cuda_native/csrc/softmax_cuda_kernel.cu#L564)
row_d_input  is a pointer, after it is zeroed we write to some bullshit location.

**Comment by Shenggan** [comment]
Thanks for reporting this bug, fixed in https://github.com/hpcaitech/FastFold/commit/ad7f0cb5d00975e698b690ecc3c44eddc446c7e1
