### ISSUE TITLE
Python Module bug

### ISSUE THREAD

**Issue by lupoglaz** [hpcaitech/FastFold#35]
This [line](https://github.com/hpcaitech/FastFold/blob/9924e7be3737453cc9dba38055a6b9cc75e7c99d/fastfold/model/fastnn/kernel/cuda_native/softmax.py#L90) should be:
return grad_input.contiguous(), None, grad_bias, None

**Comment by Shenggan** [comment]
Thanks for reporting this bug, fixed in https://github.com/hpcaitech/FastFold/pull/36

**Comment by Shenggan** [comment]
By the way, I remove scaling from fused softmax, because the different order of scaling will cause the different gradient results for q and k. 

https://github.com/hpcaitech/FastFold/blob/48ae1b08b06a373eac8fd8793a39bac0ae026222/fastfold/model/fastnn/ops.py#L163-L173
