### ISSUE TITLE
CUDA out of memory problem

### ISSUE THREAD

**Issue by ssn1771** [hpcaitech/FastFold#37]
Hi，i was tring to test H1044.fasta on NVIDIA A100，when i set the nproc_per_node=2，i met the memory problem as follows：

`RuntimeError: CUDA out of memory. Tried to allocate 77.40 GiB (GPU 0; 38.61 GiB total capacity; 13.21 GiB already allocated; 8.81 GiB free; 26.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
Is that normal？Thanks for your reply ^^

**Comment by Shenggan** [comment]
I've updated the chunk code on the latest main branch to require setting the chunk_size to significantly reduce its memory consumption when inference long sequences.

You can assign chunk_size like `model.globals.chunk_size=4` before https://github.com/hpcaitech/FastFold/blob/665e6c97a7d95d3db2df860d104fa3c456c71fe2/inference.py#L93

**Comment by ssn1771** [comment]
i have tried the new code and solved the problem, thanks a lot ^-^ 
and how do i choose the best chunk-size? Is that related to the input fasta or model size？

**Comment by Shenggan** [comment]
The memory consumption during inference is related to the length of the sequence in `input fasta`, when the sequence is relatively short, we can close chunk. After reaching a certain length, we can adjust the chunk size from large to small to avoid OOM (out of memory).

**Comment by ssn1771** [comment]
ok，thanks for your reply~
