### ISSUE TITLE
Update to newer OpenMM

### ISSUE THREAD

**Issue by peastman** [hpcaitech/FastFold#60]
The Dockerfile and environment.yml pin OpenMM to 7.5.1.  That's an old release that isn't supported anymore.  Could they be updated to the latest release, or alternatively could the pin be removed?  I don't think any code changes are needed, although there are some deprecated module names that could be updated to avoid a deprecation warning.  The patch in `openmm.patch` also isn't needed anymore.  That change has been merged upstream.

**Comment by Shenggan** [comment]
Thanks, we update openmm to 7.7.0, pr merged.

**Comment by peastman** [comment]
Thanks!
