### ISSUE TITLE
ColossalAi missing from PyPi

### ISSUE THREAD

**Issue by bernym12** [hpcaitech/FastFold#71]
When trying to install the requirements, pip failed trying to install ColossalAi and it seems it's no longer available. When trying to install ColoassalAi directly from [ColossalAI](https://github.com/hpcaitech/ColossalAI#Installation), there's a mismatch in pytorch versioning.

**Comment by Shenggan** [comment]
Could you share the installation log with us? Or you can try to create a new conda environment or use the docker image we provide.

**Comment by bernym12** [comment]
I ended up using the provided docker image. I would like to point out that it seems the `README` is misleading in the creation of the docker container. 

`cd ColossalAI
docker build -t Fastfold ./docker`

is what is written.

**Comment by Shenggan** [comment]
Thank you for the correction, have updated readme.
